### PR TITLE
Add Terraform Env variables into examples

### PR DESCRIPTION
**Pull request by sahaqaa**
This PR intended to add example on how to set Env variables to setup credentials

### CODE REVIEW

**Comment by patoarvizu** [comment]
I'm not sure this is the right example. We already have a way to pass the `client_id` and `client_secret` via non-`TF_VAR_` variables. Which is via the `OPENVPN_CLOUD_CLIENT_ID` and `OPENVPN_CLOUD_CLIENT_SECRET` variables referenced [here](https://github.com/OpenVPN/terraform-provider-openvpn-cloud/blob/main/openvpncloud/provider.go#L13C2-L14).

I think adding the variable for the company name could be useful just so we make the example be valid HCL. In practice that value will most likely be hard-coded, but I can see how some organizations might want to keep it dynamic and add it via a `.tfvars` file for example.

Regarding the `OPENVPN_CLOUD_CLIENT_ID` and `OPENVPN_CLOUD_CLIENT_SECRET` environment variables, we have that documented explicitly on the provider documentation [here](https://github.com/OpenVPN/terraform-provider-openvpn-cloud/blob/main/docs/index.md#optional), but you can change the comment on your example to reference these variables, instead of the `TF_VAR_` ones.

**Comment by sahaqaa** [comment]
From my side main intention of this change is to somehow add example that will show a way how to enter secrets via environment variables more obvious.

I've seen a few internal tickets where OpenVPN Cloud customers created tickets to Support team and shared their code examples with "client_id" and "client_secret" hardcoded.

That is why i removed this from current examples:
```
  client_id     = COMPANY_NAME_IN_OPENVPN_CLOUD
  client_secret = API_TOKEN
```

**Comment by patoarvizu** [comment]
Yeah, I think this works!

**Review by patoarvizu — APPROVED** [review]
👍

**Pull request merged**
